# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 25
    rebase-strategy: "auto"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    # Limited to 1 to eliminate risk of accidental merge conflicts.
    open-pull-requests-limit: 1
    versioning-strategy: "auto"
    directory: "/"
    schedule:
      interval: "daily"
