[workspace]
members = [
  "vmlinux",
  "btf-gen",
  "libbpf-cargo",
  "libbpf-rs",
  "examples/bpf_query",
  "examples/capable",
  "examples/runqslower",
  "examples/tc_port_whitelist",
  "examples/tcp_ca",
  "examples/tcp_option",
  "examples/tproxy",
]
resolver = "2"
