[package]
name = "tproxy"
version = "0.1.0"
edition.workspace = true
authors = ["Daniel Xu <dxu@dxuuu.xyz>"]
license = "LGPL-2.1-only OR BSD-2-Clause"

[[bin]]
name = "proxy"

[build-dependencies]
libbpf-cargo = { path = "../../libbpf-cargo" }
vmlinux = { version = "0.0", git = "https://github.com/libbpf/vmlinux.h.git", rev = "a9c092aa771310bf8b00b5018f7d40a1fdb6ec82" }

[dependencies]
anyhow = "1.0"
clap = { version = "4.0.32", default-features = false, features = ["std", "derive", "help", "usage"] }
ctrlc = "3.4"
libbpf-rs = { path = "../../libbpf-rs" }
nix = { version = "0.28", default-features = false, features = ["net", "user"] }
