[package]
name = "basic"
version = "0.1.0"
authors = ["Daniel Müller <deso@posteo.net>"]
license = "LGPL-2.1-only OR BSD-2-Clause"
edition = "2021"

[dependencies]
libbpf-rs = { path = "../../libbpf-rs" }

[build-dependencies]
libbpf-cargo = { path = "../../libbpf-cargo" }
