name: Test

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    name: Test [${{ matrix.rust }}, ${{ matrix.profile }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]
        profile: [dev]
        include:
          - rust: stable
            profile: release
    # Anything nightly is treated as informational-only.
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
    - name: "Set environmental variables"
      shell: bash
      run: |
        RUST_BACKTRACE_nightly='1'
        CFLAGS_nightly='-fsanitize=leak'
        CXXFLAGS_nightly='-fsanitize=leak'
        RUSTFLAGS_nightly='-Zsanitizer=leak'

        # A function for defining a variable conditional on the toolchain in
        # use.
        tc_var() {
          # Replace any dots in the toolchain name with underscores. Necessary
          # due to shell imposed variable naming restrictions.
          var="${1}_$(echo ${{ matrix.rust }} | tr . _)"
          echo "${1}=${!var}" >> ${GITHUB_ENV}
        }

        tc_var RUST_BACKTRACE
        tc_var RUSTFLAGS
        tc_var CFLAGS
        tc_var CXXFLAGS
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt
    - name: Install deps
      run: |
        sudo apt-get install -y clang-14 libelf-dev zlib1g-dev linux-headers-$(uname -r)
        sudo ln -s /usr/include/asm-generic /usr/include/asm
        sudo rm -f /bin/clang && sudo ln -s /usr/bin/clang-14 /bin/clang
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --profile=${{ matrix.profile }} --locked --verbose --workspace --exclude runqslower
    - name: Run tests
      # Skip tests which require sudo
      run: cargo test --profile=${{ matrix.profile }} --locked --verbose --workspace --exclude runqslower -- --skip test_sudo_  --include-ignored
    - name: Run root tests
      run: cd libbpf-rs && cargo test --profile=${{ matrix.profile }} --locked --verbose -- test_sudo_

  build-features:
    name: Build [${{ matrix.args }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - args: "features = ['vendored']"
          - args: "features = ['static']"
          # TODO: Should build without features, but that requires system
          #       libbpf and ubuntu 22.04 only has 0.5 (..?)
          #- args: "default-features = false"
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get install -y libelf-dev autopoint
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build libbpf-rs sample
        run: |
          cargo init --bin libbpf-rs-test-project
          cd libbpf-rs-test-project
          cat >> Cargo.toml <<EOF
          libbpf-rs = { version = "*", path = "../libbpf-rs", ${{ matrix.args }} }
          EOF
          cat > src/main.rs <<EOF
          fn main() {
              // Use *some* libbpf API so that we actually link against the library.
              let _linker = libbpf_rs::Linker::new("/tmp/foobar").unwrap();
          }
          EOF
          RUSTFLAGS="$RUSTFLAGS -L /usr/lib/x86_64-linux-gnu" cargo build

  build-minimum:
    name: Build using minimum versions of dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get install -y libelf-dev
      - name: Install Nightly Rust
        uses: dtolnay/rust-toolchain@nightly
      - run: cargo +nightly -Z minimal-versions update
      - name: Install minimum Rust
        uses: dtolnay/rust-toolchain@master
        with:
          # Please adjust README and rust-version field in Cargo.toml files when
          # bumping version.
          toolchain: 1.71.0
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --workspace --exclude runqslower

  build-capable:
    name: Build capable example with static libelf and libz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get install -y libelf-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: RUSTFLAGS="$RUSTFLAGS -L /usr/lib/x86_64-linux-gnu" cargo build --locked --package capable --features=static
  build-cross:
    name: Cross-compile [${{ matrix.target }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          aarch64-linux-android,
          aarch64-unknown-linux-gnu
          arm-linux-androideabi,
          armv7-linux-androideabi,
          armv7-unknown-linux-gnueabihf
          x86_64-unknown-linux-musl,
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: Install deps
        run: sudo apt-get install -y libelf-dev
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo build --lib
  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get install -y libelf-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --locked --no-deps --all-targets --tests -- -D warnings -D clippy::absolute_paths
  rustfmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check
  cargo-doc:
    name: Check documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: '-D warnings'
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get install -y libelf-dev
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --locked --no-deps
